return
{
    configurationEnableWindow = false,
    enable = true,
    invertMonsterList = false,
    showCurrentRoomOnly = true,
    showMonsterStatus = true,
    showMonsterID = true,

    mhpEnableWindow = true,
    mhpHideWhenMenu = true,
    mhpHideWhenSymbolChat = true,
    mhpHideWhenMenuUnavailable = true,
    mhpChanged = false,
    mhpAnchor = 6,
    mhpX = 100,
    mhpY = -800,
    mhpW = 990,
    mhpH = 275,
    mhpNoTitleBar = "NoTitleBar",
    mhpNoResize = "NoResize",
    mhpNoMove = "NoMove",
    mhpTransparentWindow = false,

    targetEnableWindow = false,
    targetChanged = false,
    targetAnchor = 6,
    targetX = 0,
    targetY = -200,
    targetW = 400,
    targetH = 205,
    targetNoTitleBar = "NoTitleBar",
    targetNoResize = "NoResize",
    targetNoMove = "",
    targetNoScrollbar = "NoScrollbar",
    targetTransparentWindow = false,
    targetShowMonsterName = true,
    targetShowMonsterStats = true,
    targetShowAccuracyAssist = true,
    targetAccuracyThreshold = 90,
    targetEnableActivationRates = true,
    targetEnableActivationRateItems = {
        hell = true,
        dark = true,
        blizzard = true,
        arrest = true,
        seize = true,
        chaos = true,
        havoc = true,
    },

    foRecEnableWindow = false,
    foRecShowEfficiencyBased = true,
    foRecChanged = false,
    foRecAnchor = 6,
    foRecX = 0,
    foRecY = -300,
    foRecW = 200,
    foRecH = 155,
    foRecNoTitleBar = "NoTitleBar",
    foRecNoResize = "NoResize",
    foRecNoMove = "NoMove",
    foRecNoScrollbar = "NoScrollbar",
    foRecTransparentWindow = false,

    target2EnableWindow = false,
    target2Changed = false,
    target2Anchor = 6,
    target2X = 0,
    target2Y = -300,
    target2W = 400,
    target2H = 205,
    target2NoTitleBar = "NoTitleBar",
    target2NoResize = "NoResize",
    target2NoMove = "",
    target2NoScrollbar = "NoScrollbar",
    target2TransparentWindow = false,
}
