return
{
    configurationEnableWindow = false,
    enable = false,
    invertMonsterList = false,
    showCurrentRoomOnly = false,
    showMonsterStatus = false,
    showMonsterID = false,

    mhpEnableWindow = true,
    mhpHideWhenMenu = true,
    mhpHideWhenSymbolChat = true,
    mhpHideWhenMenuUnavailable = true,
    mhpChanged = false,
    mhpAnchor = 6,
    mhpX = 100,
    mhpY = -800,
    mhpW = 990,
    mhpH = 275,
    mhpNoTitleBar = "",
    mhpNoResize = "",
    mhpNoMove = "",
    mhpTransparentWindow = false,

    targetEnableWindow = true,
    targetChanged = false,
    targetAnchor = 6,
    targetX = 0,
    targetY = -200,
    targetW = 400,
    targetH = 205,
    targetNoTitleBar = "NoTitleBar",
    targetNoResize = "NoResize",
    targetNoMove = "NoMove",
    targetNoScrollbar = "NoScrollbar",
    targetTransparentWindow = false,
    targetShowMonsterName = true,
    targetShowMonsterStats = true,
    targetShowAccuracyAssist = false,
    targetAccuracyThreshold = 90,
    targetEnableActivationRates = false,
    targetEnableActivationRateItems = {
        hell = false,
        dark = false,
        blizzard = false,
        arrest = false,
        seize = false,
        chaos = false,
        havoc = false,
    },
}
