return
{
    configurationEnableWindow = false,
    enable = true,

    ShowHealthBar = false,
    ShowMonsterStats = true,
    targetChanged = false,
    targetAnchor = 6,
    targetX = 0,
    targetY = -200,
    targetW = 400,
    targetH = 205,
    targetNoTitleBar = "NoTitleBar",
    targetNoResize = "",
    targetNoMove = "",
    targetNoScrollbar = "",
    targetTransparentWindow = false,
    targetShowAccuracyAssist = true,
    targetAccuracyThreshold = 90,
    targetEnableActivationRates = false,
    targetEnableActivationRateItems = {
        hell = true,
        dark = true,
        blizzard = true,
        arrest = true,
        seize = true,
        chaos = true,
        havoc = true,
    },
}
