return
{
    configurationEnableWindow = false,
    enable = true,

    targetEnableWindow = true,
    ShowHealthBar = true,
    ShowDamage = true,
    targetChanged = false,
    targetAnchor = 6,
    targetX = 0,
    targetY = -240,
    targetW = 275,
    targetH = 170,
    targetNoTitleBar = "NoTitleBar",
    targetNoResize = "NoResize",
    targetNoMove = "",
    targetNoScrollbar = "NoScrollbar",
    targetTransparentWindow = false,
    targetHardThreshold = 90,
    targetSpecialThreshold = 90,

    mhpEnableWindow = true,
    invertMonsterList = false,
    showCurrentRoomOnly = true,
    showMonsterStatus = true,
    showMonsterID = true,
    mhpHideWhenMenu = true,
    mhpHideWhenSymbolChat = true,
    mhpHideWhenMenuUnavailable = true,
    mhpChanged = false,
    mhpAnchor = 6,
    mhpX = 0,
    mhpY = -800,
    mhpW = 900,
    mhpH = 275,
    mhpNoTitleBar = "NoTitleBar",
    mhpNoResize = "NoResize",
    mhpNoMove = "NoMove",
    mhpTransparentWindow = false,

    foRecEnableWindow = true,
    foRecShowEfficiencyBased = false,
    foRecShowDamage = true,
    foRecChanged = false,
    foRecAnchor = 6,
    foRecX = -235,
    foRecY = -300,
    foRecW = 185,
    foRecH = 110,
    foRecNoTitleBar = "NoTitleBar",
    foRecNoResize = "NoResize",
    foRecNoMove = "",
    foRecNoScrollbar = "NoScrollbar",
    foRecTransparentWindow = false,

    target2EnableWindow = true,
    target2Changed = false,
    target2Anchor = 6,
    target2X = 215,
    target2Y = -275,
    target2W = 145,
    target2H = 135,
    target2NoTitleBar = "NoTitleBar",
    target2NoResize = "NoResize",
    target2NoMove = "NoMove",
    target2NoScrollbar = "NoScrollbar",
    target2TransparentWindow = false,

    RateEnableWindow = true,
    RateChanged = false,
    RateAnchor = 6,
    RateX = 350,
    RateY = -240,
    RateW = 115,
    RateH = 170,
    RateNoTitleBar = "NoTitleBar",
    RateNoResize = "NoResize",
    RateNoMove = "NoMove",
    RateNoScrollbar = "NoScrollbar",
    RateTransparentWindow = false,
    RateEnableActivationRates = true,
    RateEnableActivationRateItems = {
        hell = true,
        dark = true,
        blizzard = true,
        arrest = true,
        seize = true,
        chaos = true,
        havoc = true,
    },
}
