return
{
    configurationEnableWindow = false,
    enable = true,
    --reso4K = false,
    ShowRares = true,
    ShowMonsterName = true,
    ShowHealthBar = true,

    targetEnableWindow = false,
    ShowDamage = true,
    ShowHit = true,
    targetChanged = true,
    targetAnchor = 6,
    targetX = 0,
    targetY = -150,
    targetW = 285,
    targetH = 190,
    targetNoTitleBar = "NoTitleBar",
    targetNoResize = "NoResize",
    targetNoMove = "",
    targetNoScrollbar = "NoScrollbar",
    targetTransparentWindow = false,
    targetHardThreshold = 90,
    targetSpecialThreshold = 90,

    mhpEnableWindow = true,
    invertMonsterList = false,
    showCurrentRoomOnly = true,
    showMonsterResist = true,
    showMonsterStatus = true,
    showMonsterID = true,
    mhpHideWhenMenu = true,
    mhpHideWhenSymbolChat = true,
    mhpHideWhenMenuUnavailable = true,
    mhpChanged = true,
    mhpAnchor = 4,
    mhpX = 100,
    mhpY = 5,
    mhpW = 900,
    mhpH = 200,
    mhpNoTitleBar = "NoTitleBar",
    mhpNoResize = "NoResize",
    mhpNoMove = "",
    mhpTransparentWindow = true,

    foRecEnableWindow = true,
    foRecShowEfficiencyBased = false,
    foRecShowDamage = true,
    foRecChanged = false,
    foRecAnchor = 6,
    foRecX = 0,
    foRecY = -150,
    foRecW = 285,
    foRecH = 150,
    foRecNoTitleBar = "NoTitleBar",
    foRecNoResize = "NoResize",
    foRecNoMove = "",
    foRecNoScrollbar = "NoScrollbar",
    foRecTransparentWindow = false,

    target2EnableWindow = true,
    target2Changed = false,
    target2Anchor = 6,
    target2X = -215,
    target2Y = -150,
    target2W = 145,
    target2H = 130,
    target2NoTitleBar = "NoTitleBar",
    target2NoResize = "NoResize",
    target2NoMove = "",
    target2NoScrollbar = "NoScrollbar",
    target2TransparentWindow = false,

    RateEnableWindow = false,
    RateChanged = true,
    RateAnchor = 6,
    RateX = 205,
    RateY = -150,
    RateW = 120,
    RateH = 170,
    RateNoTitleBar = "NoTitleBar",
    RateNoResize = "NoResize",
    RateNoMove = "",
    RateNoScrollbar = "NoScrollbar",
    RateTransparentWindow = false,
    RateEnableActivationRates = true,
    RateEnableActivationRateItems = {
        hell = true,
        dark = true,
        blizzard = true,
        arrest = true,
        seize = true,
        chaos = true,
        havoc = true,
    },
}
