return
{
    configurationEnableWindow = false,
    enable = true,
    printItemIndex = false,
    showItemIDs = false,
    showItemData = false,
    showMaxStats = true,
    showEquippedItems = true,
    shortPBNames = true,
    ignoreMeseta = true,
    invertItemList = false,
    hideMagStats = true,
    hideMagPBs = true,
    itemNameLength = 0,
    server = 3,
    updateThrottle = 0,
    aio = {
        EnableWindow = true,
        Anchor = 8,
        X = -5,
        Y = 215,
        W = 330,
        H = 640,
        NoTitleBar = "NoTitleBar",
        NoResize = "NoResize",
        NoMove = "NoMove",
        AlwaysAutoResize = "",
        TransparentWindow = true,
        ShowButtonSaveToFile = false,
        SelectedInventory = 1,
    },
    floor = {
        EnableWindow = true,
        Anchor = 2,
        X = 455,
        Y = 100,
        W = 280,
        H = 850,
        NoTitleBar = "NoTitleBar",
        NoResize = "NoResize",
        NoMove = "NoMove",
        AlwaysAutoResize = "",
        TransparentWindow = true,
    },
    mags = {
        EnableWindow = false,
        Anchor = 1,
        X = 50,
        Y = 50,
        W = 450,
        H = 350,
        NoTitleBar = "",
        NoResize = "",
        NoMove = "",
        AlwaysAutoResize = "",
        TransparentWindow = false,
    },
}
