return
{
    configurationEnableWindow = false,
    enable = true,

    allPlayersEnableWindow = false,
    allHideWhenMenu = false,
    allHideWhenSymbolChat = false,
    allHideWhenMenuUnavailable = false,
    allPlayersChanged = false,
    allPlayersAnchor = 1,
    allPlayersX = 50,
    allPlayersY = 50,
    allPlayersW = 450,
    allPlayersH = 350,
    allPlayersNoTitleBar = "",
    allPlayersNoResize = "",
    allPlayersNoMove = "",
    allPlayersTransparentWindow = false,

    singlePlayersEnableWindow = true,
    singlePlayersShowBarText = true,
    singlePlayersShowBarMaxValue = true,

    players = {
        {
            EnableWindow = true,
            Changed = false,
            Anchor = 3,
            X = 660,
            Y = -80,
            W = 150,
            H = 74,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = true,
            SD = true,
            Invulnerability = true,
        },
        {
            EnableWindow = true,
            Changed = false,
            Anchor = 3,
            X = 810,
            Y = -80,
            W = 150,
            H = 74,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = true,
            SD = true,
            Invulnerability = true,
        },
        {
            EnableWindow = true,
            Changed = false,
            Anchor = 3,
            X = 960,
            Y = -80,
            W = 150,
            H = 74,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = true,
            SD = true,
            Invulnerability = true,
        },
        {
            EnableWindow = true,
            Changed = false,
            Anchor = 3,
            X = 1110,
            Y = -80,
            W = 150,
            H = 74,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = true,
            SD = true,
            Invulnerability = true,
        },
    },
}
