return {
    configurationWindow = false,
    globalCounterWindow = false,
    globalCounterDetailWindow = false,
    sessionCounterWindow = false,
    sessionCounterDetailWindow = false,
    sessionInfoWindow = false,
    fontScale = 1.000000,

    globalCounterDimensionsLocked = false,
    globalCounterResizeLocked = false,
    globalCounterMoveLocked = false,
    globalCounterNoTitleBar = false,
    globalCounterDifficulty = 0.000000,
    globalCounterEpisode = 0.000000,
    globalCounterSectionID = 0.000000,
    globalCounterArea = 0.000000,

    sessionCounterDimensionsLocked = false,
    sessionCounterResizeLocked = false,
    sessionCounterMoveLocked = false,
    sessionCounterNoTitleBar = false,
    sessionCounterDifficulty = 0.000000,
    sessionCounterEpisode = 0.000000,
    sessionCounterSectionID = 0.000000,
    sessionCounterArea = 0.000000,

    sessionInfoMeseta = true,
    sessionInfoMPH = true,
    sessionInfoMPHiD = true,
    sessionInfoExp = true,
    sessionInfoExpPH = true,
    sessionInfoExpPHiD = true,
    sessionInfoTime = true,
    sessionInfoDTime = true,
    sessionInfoNoTitleBar = false,
    sessionInfoMoveLocked = false,
    sessionInfoResizeLocked = false,

    globalCounterWindowDisplayMode = 1.000000,
    globalCounterDetailWindowDisplayMode = 1.000000,
    sessionCounterWindowDisplayMode = 1.000000,
    sessionCounterDetailWindowDisplayMode = 1.000000,
    sessionInfoWindowDisplayMode = 1.000000,

    globalCounterWindowTransparent = false,
    globalCounterDetailWindowTransparent = false,
    sessionCounterWindowTransparent = false,
    sessionCounterDetailWindowTransparent = false,
    sessionInfoWindowTransparent = false,

    lockRoomID = true
}
